/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Events
         * @description Журнал своей компании, новые сверху. Постранично: before —
         *     created_at последней записи предыдущей страницы.
         *
         *     Компания — только из токена. Параметра tenant_id нет: чужой журнал
         *     не запросить даже по ошибке.
         */
        get: operations["list_audit_events_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Сменить пароль. Все прежние сессии закрываются, возвращается
         *     новая пара токенов для текущего устройства.
         *
         *     Лимит — против подбора текущего пароля украденным access-токеном.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Вход. Два лимита против перебора (ASVS 6.3.1):
         *
         *     - на IP — все попытки: один адрес не перебирает много учёток;
         *     - на учётку — только неудачные: распределённый перебор одной учётки
         *       с многих адресов. Успешный вход счётчик обнуляет.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Everywhere */
        post: operations["logout_everywhere_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Кто вошёл. Доступна и до смены временного пароля: фронту нужно
         *     знать must_change_password, чтобы показать форму смены.
         */
        get: operations["read_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connectors */
        get: operations["list_connectors_api_v1_connectors_get"];
        put?: never;
        /**
         * Create Connector
         * @description Создать подключение. Учётные данные — отдельным PUT .../credentials
         *     (режим organization) или каждым сотрудником (режим per_user).
         */
        post: operations["create_connector_api_v1_connectors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Kinds
         * @description Какие системы можно подключить и какие поля у формы.
         */
        get: operations["list_kinds_api_v1_connectors_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Connectors
         * @description Подключения, которые сотрудник авторизует сам, и его состояние в них.
         */
        get: operations["my_connectors_api_v1_connectors_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth Callback
         * @description Возврат браузера сотрудника с портала: код → токены → грант.
         *
         *     Без аутентификации: кто и к какому подключению — из подписанного
         *     state. С CONNECTOR_OAUTH_RETURN_URL — редирект на фронт с
         *     connector_id и status (ok / error и error_code); без него — JSON.
         *     Ошибка — тоже 200 с кодом: браузеру некуда «упасть». Отказ в
         *     согласии приходит без code, с параметром error (OAuth 2.0).
         */
        get: operations["oauth_callback_api_v1_connectors_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connector */
        get: operations["get_connector_api_v1_connectors__connector_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Connector
         * @description Удалить подключение вместе с его документами.
         */
        delete: operations["delete_connector_api_v1_connectors__connector_id__delete"];
        options?: never;
        head?: never;
        /** Update Connector */
        patch: operations["update_connector_api_v1_connectors__connector_id__patch"];
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Credentials
         * @description Учётные данные подключения (режим organization). Только запись:
         *     в ответах — лишь credentials_set_at. Ставит синхронизацию в очередь.
         */
        put: operations["set_credentials_api_v1_connectors__connector_id__credentials_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set My Credentials
         * @description Авторизовать себя в источнике (режим per_user). Документы из
         *     листинга сотрудника появятся после ближайшей синхронизации.
         */
        put: operations["set_my_credentials_api_v1_connectors__connector_id__mine_put"];
        post?: never;
        /** Revoke My Credentials */
        delete: operations["revoke_my_credentials_api_v1_connectors__connector_id__mine_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oauth Start
         * @description Адрес авторизации на портале: фронт открывает его в браузере
         *     сотрудника, портал вернёт браузер на /connectors/oauth/callback.
         */
        post: operations["oauth_start_api_v1_connectors__connector_id__oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_connectors__connector_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Now
         * @description «Синхронизировать сейчас»: 202, работа — в воркере; прогресс — в runs.
         */
        post: operations["sync_now_api_v1_connectors__connector_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connector
         * @description Проверить учётные данные без загрузки документов.
         */
        post: operations["test_connector_api_v1_connectors__connector_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faq/answers/{answer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rate Answer
         * @description 👍 (1) или 👎 (-1) к своему ответу. Нужно отчёту о пробелах и eval.
         */
        patch: operations["rate_answer_api_v1_faq_answers__answer_id__patch"];
        trace?: never;
    };
    "/api/v1/faq/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Faq */
        post: operations["ask_faq_api_v1_faq_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faq/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Faq
         * @description Отладка поиска для eval (BH-5): top-K с расстояниями, без порога и LLM.
         *
         *     Только ADMIN: показывает сырые выдержки и расстояния, которых нет в
         *     продуктовом ответе. Компания — из токена, как везде.
         */
        post: operations["search_faq_api_v1_faq_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gaps
         * @description Чего не хватает в документах компании — важное сверху (BH-23).
         *
         *     Только пробелы (gap) и отказы модели при найденных выдержках
         *     (model_refusal); остальные промахи — внутренний мониторинг. Отчёт
         *     обновляется раз в сутки ночной задачей. Компания — из токена.
         */
        get: operations["list_gaps_api_v1_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gaps/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Gap Status
         * @description Отметить пробел: в работе, закрыт (документ загружен), отклонён.
         *
         *     Статус переживает ночную пересборку, пока группа узнаётся по общим
         *     вопросам.
         */
        patch: operations["set_gap_status_api_v1_gaps__cluster_id__patch"];
        trace?: never;
    };
    "/api/v1/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Terms
         * @description Словарь сокращений своей компании (M5, BH-14).
         */
        get: operations["list_terms_api_v1_glossary_get"];
        put?: never;
        /**
         * Create Term
         * @description Добавить сокращение. Действует со следующего вопроса: расшифровка
         *     дописывается к вопросу перед поиском, переиндексация не нужна.
         */
        post: operations["create_term_api_v1_glossary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/glossary/{term_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Term */
        delete: operations["delete_term_api_v1_glossary__term_id__delete"];
        options?: never;
        head?: never;
        /** Update Term */
        patch: operations["update_term_api_v1_glossary__term_id__patch"];
        trace?: never;
    };
    "/api/v1/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invites
         * @description Последние ссылки компании с их состоянием; токенов в ответе нет.
         */
        get: operations["list_invites_api_v1_invites_get"];
        put?: never;
        /**
         * Create Invite
         * @description Ссылка-приглашение в свою компанию. Токен — в ответе один раз.
         */
        post: operations["create_invite_api_v1_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invite
         * @description Завести учётку сотрудника по ссылке и сразу войти.
         */
        post: operations["accept_invite_api_v1_invites_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Invite
         * @description В какую компанию ведёт ссылка — для карточки «Присоединиться».
         */
        post: operations["preview_invite_api_v1_invites_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_api_v1_invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Lead
         * @description Заявка на созвон со страницы тарифов (досье 10.1). Без входа:
         *     лимит по IP и общий суточный, ловушка для ботов, согласие с версией
         *     политики. Команда видит заявки в `cli leads list`.
         */
        post: operations["submit_lead_api_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lead Form
         * @description Настройки формы записи на созвон — без входа.
         */
        get: operations["lead_form_api_v1_leads_form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_v1_materials_get"];
        put?: never;
        /**
         * Create Material
         * @description Создать материал и сразу поставить его в очередь на индексацию.
         */
        post: operations["create_material_api_v1_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Material
         * @description Загрузить документ файлом.
         *
         *     title — человеческое название («Правила отбора в акселератор»), а не
         *     имя файла: оно уходит в крошки эмбеддинга и в подписи источников.
         *     Формат определяется по содержимому, а не по расширению и не по
         *     Content-Type, который присылает клиент.
         */
        post: operations["upload_material_api_v1_materials_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_v1_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Delete Material */
        delete: operations["delete_material_api_v1_materials__material_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Material
         * @description Переименовать. Материал встаёт в очередь на переиндексацию.
         */
        patch: operations["update_material_api_v1_materials__material_id__patch"];
        trace?: never;
    };
    "/api/v1/materials/{material_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Material
         * @description Переиндексировать: 202 сразу, работа — в воркере.
         *
         *     Прогресс — по статусу в GET /materials/{id}.
         */
        post: operations["ingest_material_api_v1_materials__material_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description Пул кредитов своей компании: сколько потрачено и сколько осталось.
         *
         *     Только ADMIN: пул общий, решать, что делать при исчерпании (докупить
         *     места, подождать месяц), — администратору компании. Компания — из
         *     токена, параметра tenant_id нет.
         */
        get: operations["get_usage_api_v1_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerDiagnosticsResponse
         * @description Только для ADMIN: модель, версия промпта, токены — для eval (E5).
         */
        AnswerDiagnosticsResponse: {
            /** Credits */
            credits: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string | null;
            /** Model Version */
            model_version: string | null;
            /** Nearest Distance */
            nearest_distance: number | null;
            /** Output Tokens */
            output_tokens: number;
            /** Prompt Version */
            prompt_version: string;
        };
        /**
         * AnswerOrigin
         * @description Откуда взят ответ.
         *
         *     DOCUMENTS — из выдержек документов компании, со ссылками.
         *     GENERAL_KNOWLEDGE — в документах ответа не нашлось, модель ответила
         *     из общих знаний. Такой ответ всегда помечен: первой строкой текста
         *     (GENERAL_ANSWER_PREFIX) и этим полем — фронт показывает предупреждение
         *     по полю, не разбирая текст.
         *     NONE — в документах ответа нет, а компания выбрала строгий режим:
         *     честный отказ (REFUSAL_ANSWER: NOT_FOUND_ANSWER и совет уточнить) без
         *     ответа из общих знаний.
         * @enum {string}
         */
        AnswerOrigin: "documents" | "general_knowledge" | "none";
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ip */
            ip: string | null;
            /** Request Id */
            request_id: string | null;
            /** Target Id */
            target_id: string | null;
            /** Target Type */
            target_type: string | null;
        };
        /** Body_upload_material_api_v1_materials_upload_post */
        Body_upload_material_api_v1_materials_upload_post: {
            /**
             * File
             * @description docx, pdf, txt или md
             */
            file: string;
            /** Title */
            title: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ConnectorCreateRequest */
        ConnectorCreateRequest: {
            /** Config */
            config?: {
                [key: string]: string;
            };
            /** Kind */
            kind: string;
            /** Modules */
            modules: string[];
            /** Name */
            name: string;
            /** Sync Interval Minutes */
            sync_interval_minutes?: number | null;
        };
        /**
         * ConnectorKindResponse
         * @description Вид коннектора из каталога — для формы подключения на фронте.
         *
         *     credential_fields — что вводит админ (organization) или сотрудник
         *     (per_user без OAuth); app_credential_fields — секреты приложения,
         *     которые в режиме per_user задаёт админ; oauth — сотрудник
         *     авторизуется редиректом (POST /connectors/{id}/oauth/start), а
         *     oauth_callback_url админ вписывает в карточку приложения.
         */
        ConnectorKindResponse: {
            /** App Credential Fields */
            app_credential_fields?: components["schemas"]["FieldSpecResponse"][];
            /** Config Fields */
            config_fields: components["schemas"]["FieldSpecResponse"][];
            /** Credential Fields */
            credential_fields: components["schemas"]["FieldSpecResponse"][];
            /** Extra */
            extra?: {
                [key: string]: string;
            };
            /** Kind */
            kind: string;
            mode: components["schemas"]["ConnectorMode"];
            /** Modules */
            modules: components["schemas"]["ModuleSpecResponse"][];
            /**
             * Oauth
             * @default false
             */
            oauth: boolean;
            /** Oauth Callback Url */
            oauth_callback_url?: string | null;
            /** Title */
            title: string;
        };
        /**
         * ConnectorMode
         * @description Как коннектор получает документы и права (DECISIONS «Коннекторы»).
         *
         *     ORGANIZATION — админ подключает одну учётную запись на компанию,
         *     адаптер выгружает документы и их ACL (Confluence). PER_USER — админ
         *     ставит приложение, каждый сотрудник авторизует его сам; документ
         *     виден сотруднику, если есть в ЕГО листинге (Битрикс24, Яндекс).
         * @enum {string}
         */
        ConnectorMode: "organization" | "per_user";
        /** ConnectorResponse */
        ConnectorResponse: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Credentials Set At */
            credentials_set_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Last Error Code */
            last_error_code: string | null;
            /** Last Sync At */
            last_sync_at: string | null;
            mode: components["schemas"]["ConnectorMode"];
            /** Modules */
            modules: string[];
            /** Name */
            name: string;
            status: components["schemas"]["ConnectorStatus"];
            /** Sync Interval Minutes */
            sync_interval_minutes: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConnectorStatus
         * @enum {string}
         */
        ConnectorStatus: "active" | "paused" | "error";
        /** ConnectorTestResponse */
        ConnectorTestResponse: {
            /** Error Code */
            error_code?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ConnectorUpdateRequest */
        ConnectorUpdateRequest: {
            /** Config */
            config?: {
                [key: string]: string;
            } | null;
            /** Modules */
            modules?: string[] | null;
            /** Name */
            name?: string | null;
            status?: components["schemas"]["ConnectorStatus"] | null;
            /** Sync Interval Minutes */
            sync_interval_minutes?: number | null;
        };
        /**
         * CredentialsRequest
         * @description Учётные данные — только на запись: в ответах их нет.
         */
        CredentialsRequest: {
            /** Credentials */
            credentials: {
                [key: string]: string;
            };
        };
        /**
         * FaqAnswerResponse
         * @description Ответ ассистента.
         *
         *     origin:
         *     - documents — ответ по документам компании, sources — выдержки;
         *     - general_knowledge — в документах ответа нет, ответ из общих
         *       знаний: content начинается с GENERAL_ANSWER_PREFIX («В документах
         *       компании ответа нет. Ниже — общая информация, не из документов
         *       компании:»), sources пуст. Фронт обязан показать это явно
         *       (плашка), а не только текстом;
         *     - none — в документах ответа нет, компания в строгом режиме (по
         *       умолчанию), или провайдер отфильтровал ответ: content начинается с
         *       NOT_FOUND_ANSWER («В документах компании ответа нет.»), дальше —
         *       совет уточнить у руководителя или в профильном отделе; sources пуст.
         *
         *     answer_id — для оценки 👍/👎 (PATCH /faq/answers/{answer_id}).
         */
        FaqAnswerResponse: {
            /** Answer Given */
            answer_given: boolean;
            /** Answer Id */
            answer_id: string | null;
            /** Content */
            content: string;
            diagnostics?: components["schemas"]["AnswerDiagnosticsResponse"] | null;
            origin: components["schemas"]["AnswerOrigin"];
            /** Sources */
            sources: components["schemas"]["FaqSourceResponse"][];
        };
        /** FaqQuestionRequest */
        FaqQuestionRequest: {
            /** Question */
            question: string;
        };
        /**
         * FaqSearchMatch
         * @description Форма ответа согласована с клиентом eval (ml-backend-contracts, 3).
         */
        FaqSearchMatch: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Content */
            content: string;
            /** Distance */
            distance: number;
            /** Fulltext Rank */
            fulltext_rank: number | null;
            /** Heading Path */
            heading_path: string[];
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Material Title */
            material_title: string;
            /** Position */
            position: number;
        };
        /** FaqSearchRequest */
        FaqSearchRequest: {
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Question */
            question: string;
            retriever?: components["schemas"]["Retriever"] | null;
        };
        /** FaqSearchResponse */
        FaqSearchResponse: {
            /** Matches */
            matches: components["schemas"]["FaqSearchMatch"][];
        };
        /** FaqSourceResponse */
        FaqSourceResponse: {
            /** Content */
            content: string;
            /** Heading Path */
            heading_path: string[];
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Position */
            position: number;
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Value
             * @enum {integer}
             */
            value: -1 | 1;
        };
        /** FieldSpecResponse */
        FieldSpecResponse: {
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /** Secret */
            secret: boolean;
            /** Title */
            title: string;
        };
        /**
         * GapClusterResponse
         * @description Пробел: тема, чего не хватает, насколько это важно.
         *
         *     sample_questions — последние вопросы группы после mask_pii. Это текст
         *     сотрудников: фронт выводит его как текст, не как разметку.
         */
        GapClusterResponse: {
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Missing */
            missing: string;
            /** Priority */
            priority: number;
            /** Question Count */
            question_count: number;
            /** Sample Questions */
            sample_questions: string[];
            status: components["schemas"]["GapStatus"];
            /** Title */
            title: string;
            /** User Count */
            user_count: number;
        };
        /** GapReportResponse */
        GapReportResponse: {
            /** Clusters */
            clusters: components["schemas"]["GapClusterResponse"][];
        };
        /**
         * GapStatus
         * @description Что админ сделал с пробелом в отчёте (BH-22).
         * @enum {string}
         */
        GapStatus: "new" | "in_progress" | "resolved" | "dismissed";
        /** GapStatusRequest */
        GapStatusRequest: {
            status: components["schemas"]["GapStatus"];
        };
        /**
         * GlossaryTermCreateRequest
         * @description «ДМС» → «добровольное медицинское страхование».
         */
        GlossaryTermCreateRequest: {
            /** Expansion */
            expansion: string;
            /** Term */
            term: string;
        };
        /** GlossaryTermResponse */
        GlossaryTermResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expansion */
            expansion: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Term */
            term: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GlossaryTermUpdateRequest */
        GlossaryTermUpdateRequest: {
            /** Expansion */
            expansion?: string | null;
            /** Term */
            term?: string | null;
        };
        /**
         * GrantStatus
         * @description Состояние авторизации сотрудника в коннекторе per_user.
         * @enum {string}
         */
        GrantStatus: "active" | "expired" | "revoked";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestResponse */
        IngestResponse: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            status: components["schemas"]["MaterialStatus"];
        };
        /** InviteAcceptRequest */
        InviteAcceptRequest: {
            /** Company Code */
            company_code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** InviteCreateRequest */
        InviteCreateRequest: {
            /** Email Domain */
            email_domain?: string | null;
            /** Max Uses */
            max_uses?: number | null;
            /**
             * Ttl Days
             * @default 7
             */
            ttl_days: number;
        };
        /** InviteCreatedResponse */
        InviteCreatedResponse: {
            /** Company Code */
            company_code: string;
            invite: components["schemas"]["InviteResponse"];
            /** Token */
            token: string;
        };
        /** InvitePreviewResponse */
        InvitePreviewResponse: {
            /** Company Name */
            company_name: string;
            /** Email Domain */
            email_domain: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** InviteResponse */
        InviteResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email Domain */
            email_domain: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max Uses */
            max_uses: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "expired" | "revoked" | "used_up";
            /** Uses */
            uses: number;
        };
        /** InviteTokenRequest */
        InviteTokenRequest: {
            /** Company Code */
            company_code: string;
            /** Token */
            token: string;
        };
        /**
         * LeadFormResponse
         * @description Что нужно форме записи: открыта ли она, политика, даты и окна.
         */
        LeadFormResponse: {
            /** Enabled */
            enabled: boolean;
            /**
             * First Date
             * Format: date
             */
            first_date: string;
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
            /** Policy Url */
            policy_url: string | null;
            /** Policy Version */
            policy_version: string | null;
            /** Slots */
            slots: string[];
            /** Timezone */
            timezone: string;
        };
        /** LeadReceivedResponse */
        LeadReceivedResponse: {
            /**
             * Status
             * @default received
             * @constant
             */
            status: "received";
        };
        /** LeadRequest */
        LeadRequest: {
            /** Comment */
            comment?: string | null;
            /** Company Name */
            company_name: string;
            /** Consent */
            consent: boolean;
            /** Contact Name */
            contact_name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone: string;
            /** Policy Version */
            policy_version: string;
            /**
             * Preferred Date
             * Format: date
             */
            preferred_date: string;
            /** Preferred Slot */
            preferred_slot: string;
            /** Seats */
            seats: number;
            /** @default base */
            tariff: components["schemas"]["LeadTariff"];
            /**
             * Website
             * @default
             */
            website: string;
        };
        /**
         * LeadTariff
         * @enum {string}
         */
        LeadTariff: "base" | "custom";
        /** LoginRequest */
        LoginRequest: {
            /** Company Code */
            company_code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MaterialCreateRequest
         * @description Документ компании в виде текста (Markdown или простой текст).
         *
         *     title — человеческое название («Положение об отпусках»), а не имя
         *     файла: оно уходит в крошки эмбеддинга и в подписи источников.
         */
        MaterialCreateRequest: {
            /** Content */
            content: string;
            /** Title */
            title: string;
        };
        /**
         * MaterialResponse
         * @description Материал без содержимого: клиенту нужен статус, а не текст.
         */
        MaterialResponse: {
            /** Connector Id */
            connector_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Indexed At */
            indexed_at: string | null;
            /** Source Filename */
            source_filename: string | null;
            /** Source Format */
            source_format: string | null;
            /** Source Size */
            source_size: number | null;
            /** Source Url */
            source_url?: string | null;
            status: components["schemas"]["MaterialStatus"];
            /** Status Error */
            status_error: string | null;
            /** Synced At */
            synced_at?: string | null;
            /** Title */
            title: string;
            /**
             * Visibility
             * @default tenant
             */
            visibility: string;
        };
        /**
         * MaterialStatus
         * @description Где материал на пути к поиску.
         *
         *     PENDING — поставлен в очередь, PROCESSING — воркер нарезает и считает
         *     эмбеддинги, READY — чанки на месте, FAILED — не получилось (причина —
         *     кодом в status_error, подробности только в логе).
         * @enum {string}
         */
        MaterialStatus: "pending" | "processing" | "ready" | "failed";
        /** MaterialUpdateRequest */
        MaterialUpdateRequest: {
            /** Title */
            title: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Company Code */
            company_code: string;
            /** Company Name */
            company_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Must Change Password */
            must_change_password: boolean;
            role: components["schemas"]["UserRole"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** ModuleSpecResponse */
        ModuleSpecResponse: {
            /** Name */
            name: string;
            /** Title */
            title: string;
        };
        /**
         * MyConnectorResponse
         * @description Коннектор режима per_user глазами сотрудника: подключён ли он сам.
         */
        MyConnectorResponse: {
            /** Grant Error Code */
            grant_error_code: string | null;
            grant_status: components["schemas"]["GrantStatus"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /**
             * Oauth
             * @default false
             */
            oauth: boolean;
        };
        /**
         * OAuthCallbackResponse
         * @description Ответ обратного вызова, когда CONNECTOR_OAUTH_RETURN_URL не задан.
         */
        OAuthCallbackResponse: {
            /** Connector Id */
            connector_id: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Ok */
            ok: boolean;
        };
        /**
         * OAuthStartResponse
         * @description Куда отправить браузер сотрудника. state внутри адреса подписан
         *     и привязан к сотруднику и подключению.
         */
        OAuthStartResponse: {
            /** Authorize Url */
            authorize_url: string;
        };
        /** PasswordResetResponse */
        PasswordResetResponse: {
            /** Temporary Password */
            temporary_password: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Retriever
         * @description Как искать выдержки (M1, BH-12).
         *
         *     VECTOR — только векторный поиск, порог на каждой выдержке.
         *     HYBRID — вектор + полнотекст, слияние RRF; порог — на лучшем
         *     векторном кандидате (скор RRF зависит только от рангов).
         * @enum {string}
         */
        Retriever: "vector" | "hybrid";
        /** SyncRequestedResponse */
        SyncRequestedResponse: {
            /**
             * Connector Id
             * Format: uuid
             */
            connector_id: string;
            /** Queued */
            queued: boolean;
        };
        /** SyncRunResponse */
        SyncRunResponse: {
            /** Error Code */
            error_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Trigger */
            trigger: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UsageResponse
         * @description Расход пула кредитов компании за текущий месяц.
         */
        UsageResponse: {
            /** Credits Per Seat */
            credits_per_seat: number;
            /** Exhausted */
            exhausted: boolean;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Pool */
            pool: number;
            /** Remaining */
            remaining: number;
            /** Seats */
            seats: number;
            /** Used */
            used: number;
            /** Warn At Percent */
            warn_at_percent: number;
            /** Warning */
            warning: boolean;
        };
        /**
         * UserCreateRequest
         * @description Новый сотрудник. Без password система сгенерирует временный.
         */
        UserCreateRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password?: string | null;
            /** @default employee */
            role: components["schemas"]["UserRole"];
        };
        /** UserCreatedResponse */
        UserCreatedResponse: {
            /** Temporary Password */
            temporary_password: string | null;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * UserResponse
         * @description Пользователь без пароля, хеша и версии токенов.
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /** Must Change Password */
            must_change_password: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @description Роль сотрудника внутри своей компании.
         *
         *     ADMIN — управляет документами и пользователями компании, видит
         *     отладку поиска и отчёт о пробелах. EMPLOYEE — задаёт вопросы.
         *     Заводить компании (тенанты) не может ни одна роль: это делает
         *     команда Kronto через CLI на сервере (см. corp_ed.cli).
         * @enum {string}
         */
        UserRole: "admin" | "employee";
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_audit_events_api_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_everywhere_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connectors_api_v1_connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"][];
                };
            };
        };
    };
    create_connector_api_v1_connectors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kinds_api_v1_connectors_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorKindResponse"][];
                };
            };
        };
    };
    my_connectors_api_v1_connectors_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyConnectorResponse"][];
                };
            };
        };
    };
    oauth_callback_api_v1_connectors_oauth_callback_get: {
        parameters: {
            query: {
                state: string;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthCallbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connector_api_v1_connectors__connector_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connector_api_v1_connectors__connector_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connector_api_v1_connectors__connector_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_credentials_api_v1_connectors__connector_id__credentials_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_my_credentials_api_v1_connectors__connector_id__mine_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_my_credentials_api_v1_connectors__connector_id__mine_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_start_api_v1_connectors__connector_id__oauth_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_connectors__connector_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_now_api_v1_connectors__connector_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRequestedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connector_api_v1_connectors__connector_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_answer_api_v1_faq_answers__answer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_faq_api_v1_faq_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaqQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaqAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_faq_api_v1_faq_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaqSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaqSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gaps_api_v1_gaps_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["GapStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_gap_status_api_v1_gaps__cluster_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GapStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapClusterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_terms_api_v1_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermResponse"][];
                };
            };
        };
    };
    create_term_api_v1_glossary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryTermCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_term_api_v1_glossary__term_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_term_api_v1_glossary__term_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryTermUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_api_v1_invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"][];
                };
            };
        };
    };
    create_invite_api_v1_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_api_v1_invites_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_invite_api_v1_invites_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_api_v1_invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_lead_api_v1_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadReceivedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lead_form_api_v1_leads_form_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadFormResponse"];
                };
            };
        };
    };
    list_materials_api_v1_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"][];
                };
            };
        };
    };
    create_material_api_v1_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_material_api_v1_materials_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_material_api_v1_materials_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_v1_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_api_v1_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_material_api_v1_materials__material_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_material_api_v1_materials__material_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_api_v1_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
