"""glossary terms

Revision ID: 019109ccbb0a
Revises: 6c97d643b0b6
Create Date: 2026-09-25 12:21:36.809125

Словарь сокращений компании (M5, BH-14). Тенант-таблица: под RLS с
FORCE, как остальные (core/db_policies.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from corp_ed.core.db_policies import rls_statements


# revision identifiers, used by Alembic.
revision: str = '019109ccbb0a'
down_revision: Union[str, Sequence[str], None] = '6c97d643b0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=64), nullable=False),
    sa.Column('expansion', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_tenant_id'), 'glossary_terms', ['tenant_id'], unique=False)
    op.create_index('uq_glossary_terms_tenant_term', 'glossary_terms', ['tenant_id', sa.literal_column('lower(term)')], unique=True)
    # ### end Alembic commands ###
    for statement in rls_statements(("glossary_terms",)):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_glossary_terms_tenant_term', table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_tenant_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    # ### end Alembic commands ###
