"""material status and ingest job queue

Revision ID: 082d6d6c3590
Revises: 73493006a1b1
Create Date: 2026-09-25 11:36:05.204629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

MATERIAL_STATUS = ("PENDING", "PROCESSING", "READY", "FAILED")
JOB_STATUS = ("QUEUED", "RUNNING", "DONE", "FAILED")


# revision identifiers, used by Alembic.
revision: str = '082d6d6c3590'
down_revision: Union[str, Sequence[str], None] = '73493006a1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Типы — явно, через postgresql.ENUM: sa.Enum в add_column тип не
    # создаёт (ARCHITECTURE.md, раздел «Миграции»).
    postgresql.ENUM(*MATERIAL_STATUS, name="materialstatus").create(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM(*JOB_STATUS, name="ingestjobstatus").create(
        op.get_bind(), checkfirst=True
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM(*JOB_STATUS, name='ingestjobstatus', create_type=False), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=64), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_jobs_queue', 'ingest_jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_tenant_id'), 'ingest_jobs', ['tenant_id'], unique=False)
    op.create_index('uq_ingest_jobs_active_material', 'ingest_jobs', ['material_id'], unique=True, postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.add_column('materials', sa.Column('status', postgresql.ENUM(*MATERIAL_STATUS, name='materialstatus', create_type=False), server_default='PENDING', nullable=False))
    op.add_column('materials', sa.Column('status_error', sa.String(length=64), nullable=True))
    op.add_column('materials', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Уже проиндексированные до очереди материалы — готовы, остальные
    # ждут переиндексации (python -m corp_ed.cli reindex).
    op.execute(
        "UPDATE materials SET status = 'READY', indexed_at = now() "
        "WHERE EXISTS (SELECT 1 FROM chunks WHERE chunks.material_id = materials.id)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'indexed_at')
    op.drop_column('materials', 'status_error')
    op.drop_column('materials', 'status')
    op.drop_index('uq_ingest_jobs_active_material', table_name='ingest_jobs', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.drop_index(op.f('ix_ingest_jobs_tenant_id'), table_name='ingest_jobs')
    op.drop_index('ix_ingest_jobs_queue', table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###
    postgresql.ENUM(name="ingestjobstatus").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="materialstatus").drop(op.get_bind(), checkfirst=True)
