"""audit events table

Revision ID: 1bc0bfec7e55
Revises: 045621dbe193
Create Date: 2026-09-25 11:21:11.718512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from corp_ed.core.db_policies import audit_append_only_statements
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bc0bfec7e55'
down_revision: Union[str, Sequence[str], None] = '045621dbe193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Журнал только дописывается: триггер против UPDATE и DELETE.
    # SQL — в corp_ed.core.db_policies, его же применяют тесты.
    for statement in audit_append_only_statements():
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_tenant_created', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
