"""invites

Revision ID: 3a9c582a28d6
Revises: eaaa2fcbfb12
Create Date: 2026-09-28 14:22:38.813514

Ссылки-приглашения в компанию (решение 28.09): админ отправляет ссылку,
по ней человек сам заводит учётку сотрудника. Хранится только sha256
токена. Таблица тенантская — под RLS с FORCE (core/db_policies.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from corp_ed.core.db_policies import rls_statements


# revision identifiers, used by Alembic.
revision: str = '3a9c582a28d6'
down_revision: Union[str, Sequence[str], None] = 'eaaa2fcbfb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('email_domain', sa.String(length=253), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('max_uses > 0', name='ck_invites_max_uses_positive'),
    sa.CheckConstraint('uses >= 0 AND uses <= max_uses', name='ck_invites_uses'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invites_tenant_id'), 'invites', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for statement in rls_statements(('invites',)):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_tenant_id'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
