"""connectors core

Revision ID: 42a0ae63f5ff
Revises: e512b41ef60f
Create Date: 2026-09-25 16:32:36.904694

Коннекторы к источникам документов, этап 1 (DECISIONS «Коннекторы»):
подключения, гранты сотрудников, журнал запусков, очередь воркера,
права на документ (material_access) и поля источника у материалов.
Тенантские таблицы — под RLS с FORCE (core/db_policies.py); очередь
connector_sync_jobs — нет, как ingest_jobs.

Индекс уникальности sha256 сужается до ручных загрузок: один файл на
двух дисках — два документа с разными ссылками.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from corp_ed.core.db_policies import rls_statements

# revision identifiers, used by Alembic.
revision: str = '42a0ae63f5ff'
down_revision: Union[str, Sequence[str], None] = 'e512b41ef60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('modules', sa.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('credentials_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("mode IN ('organization', 'per_user')", name='ck_connectors_mode'),
    sa.CheckConstraint("status IN ('active', 'paused', 'error')", name='ck_connectors_status'),
    sa.CheckConstraint('sync_interval_minutes BETWEEN 15 AND 1440', name='ck_connectors_sync_interval'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.create_table('connector_sync_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=16), server_default='schedule', nullable=False),
    # Тот же тип, что у ingest_jobs: он уже существует, второй раз не создаётся.
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='ingestjobstatus', create_type=False), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=64), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_sync_jobs_tenant_id'), 'connector_sync_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_sync_jobs_queue', 'connector_sync_jobs', ['status', 'run_after'], unique=False)
    op.create_index('uq_sync_jobs_active_connector', 'connector_sync_jobs', ['connector_id'], unique=True, postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.create_table('connector_sync_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'partial', 'failed')", name='ck_sync_runs_status'),
    sa.CheckConstraint("trigger IN ('schedule', 'manual')", name='ck_sync_runs_trigger'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_sync_runs_tenant_id'), 'connector_sync_runs', ['tenant_id'], unique=False)
    op.create_index('ix_sync_runs_connector_started', 'connector_sync_runs', ['connector_id', 'started_at'], unique=False)
    op.create_table('connector_user_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'expired', 'revoked')", name='ck_grants_status'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'user_id', name='uq_grant_connector_user')
    )
    op.create_index(op.f('ix_connector_user_grants_connector_id'), 'connector_user_grants', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_user_grants_tenant_id'), 'connector_user_grants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_connector_user_grants_user_id'), 'connector_user_grants', ['user_id'], unique=False)
    op.create_table('material_access',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', 'user_id')
    )
    op.create_index(op.f('ix_material_access_tenant_id'), 'material_access', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_material_access_user_id'), 'material_access', ['user_id'], unique=False)
    op.add_column('materials', sa.Column('connector_id', sa.Uuid(), nullable=True))
    op.add_column('materials', sa.Column('external_id', sa.String(length=512), nullable=True))
    op.add_column('materials', sa.Column('source_url', sa.String(length=2048), nullable=True))
    op.add_column('materials', sa.Column('external_version', sa.String(length=128), nullable=True))
    op.add_column('materials', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('materials', sa.Column('visibility', sa.String(length=16), server_default='tenant', nullable=False))
    op.create_index(op.f('ix_materials_connector_id'), 'materials', ['connector_id'], unique=False)
    op.create_index('uq_materials_connector_external_id', 'materials', ['connector_id', 'external_id'], unique=True, postgresql_where=sa.text('connector_id IS NOT NULL'))
    op.create_foreign_key('fk_materials_connector_id', 'materials', 'connectors', ['connector_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    op.create_check_constraint(
        'ck_materials_visibility', 'materials', "visibility IN ('tenant', 'restricted')"
    )
    op.drop_index('uq_materials_tenant_sha256', table_name='materials')
    op.create_index(
        'uq_materials_tenant_sha256', 'materials', ['tenant_id', 'source_sha256'],
        unique=True,
        postgresql_where=sa.text('source_sha256 IS NOT NULL AND connector_id IS NULL'),
    )
    for statement in rls_statements(
        ('connectors', 'connector_user_grants', 'connector_sync_runs', 'material_access')
    ):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # Документы коннекторов вместе с ними: без connector_id они потеряли
    # бы источник и стали бы неотличимы от ручных загрузок. Под FORCE RLS
    # владелец без app.tenant_id не видит ни строки — снимаем FORCE на
    # время удаления (правило из core/db_policies.py).
    op.execute("ALTER TABLE materials NO FORCE ROW LEVEL SECURITY")
    op.execute("DELETE FROM materials WHERE connector_id IS NOT NULL")
    op.execute("ALTER TABLE materials FORCE ROW LEVEL SECURITY")
    op.drop_index('uq_materials_tenant_sha256', table_name='materials')
    op.create_index(
        'uq_materials_tenant_sha256', 'materials', ['tenant_id', 'source_sha256'],
        unique=True, postgresql_where=sa.text('source_sha256 IS NOT NULL'),
    )
    op.drop_constraint('ck_materials_visibility', 'materials', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_materials_connector_id', 'materials', type_='foreignkey')
    op.drop_index('uq_materials_connector_external_id', table_name='materials', postgresql_where=sa.text('connector_id IS NOT NULL'))
    op.drop_index(op.f('ix_materials_connector_id'), table_name='materials')
    op.drop_column('materials', 'visibility')
    op.drop_column('materials', 'synced_at')
    op.drop_column('materials', 'external_version')
    op.drop_column('materials', 'source_url')
    op.drop_column('materials', 'external_id')
    op.drop_column('materials', 'connector_id')
    op.drop_index(op.f('ix_material_access_user_id'), table_name='material_access')
    op.drop_index(op.f('ix_material_access_tenant_id'), table_name='material_access')
    op.drop_table('material_access')
    op.drop_index(op.f('ix_connector_user_grants_user_id'), table_name='connector_user_grants')
    op.drop_index(op.f('ix_connector_user_grants_tenant_id'), table_name='connector_user_grants')
    op.drop_index(op.f('ix_connector_user_grants_connector_id'), table_name='connector_user_grants')
    op.drop_table('connector_user_grants')
    op.drop_index('ix_sync_runs_connector_started', table_name='connector_sync_runs')
    op.drop_index(op.f('ix_connector_sync_runs_tenant_id'), table_name='connector_sync_runs')
    op.drop_table('connector_sync_runs')
    op.drop_index('uq_sync_jobs_active_connector', table_name='connector_sync_jobs', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.drop_index('ix_sync_jobs_queue', table_name='connector_sync_jobs')
    op.drop_index(op.f('ix_connector_sync_jobs_tenant_id'), table_name='connector_sync_jobs')
    op.drop_table('connector_sync_jobs')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
