"""add heading_path and embed_text to chunks

Revision ID: 453c802d4852
Revises: 2179673eb758
Create Date: 2026-09-25 10:58:57.903807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453c802d4852'
down_revision: Union[str, Sequence[str], None] = '2179673eb758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Нарезка v2 (BH-3): у чанка появляются путь заголовков и отдельное
    # представление для эмбеддинга. chunks.content с этой ревизии хранит
    # llm_text (крошки + Markdown). Старые чанки остаются валидными, но
    # без крошек: их обновит переиндексация.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('heading_path', sa.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('chunks', sa.Column('embed_text', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embed_text')
    op.drop_column('chunks', 'heading_path')
    # ### end Alembic commands ###
