"""leads

Revision ID: 6a5fa0240814
Revises: 3a9c582a28d6
Create Date: 2026-09-28 14:36:22.909887

Заявки на созвон со страницы тарифов (досье 10.1, решение 28.09). Не
тенантская: клиента ещё нет, RLS не нужен; читает только команда (CLI).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5fa0240814'
down_revision: Union[str, Sequence[str], None] = '3a9c582a28d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('tariff', sa.String(length=16), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_slot', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'contacted', 'scheduled', 'rejected')", name='ck_leads_status'),
    sa.CheckConstraint("tariff IN ('base', 'custom')", name='ck_leads_tariff'),
    sa.CheckConstraint('seats > 0', name='ck_leads_seats_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
