"""chunks fulltext

Revision ID: 6c97d643b0b6
Revises: 8a2ebb872f4a
Create Date: 2026-09-25 12:14:56.954320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c97d643b0b6'
down_revision: Union[str, Sequence[str], None] = '8a2ebb872f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Полнотекстовая ветка гибридного поиска (M1, BH-12). Генерируемая
    # колонка STORED: ADD COLUMN переписывает таблицу под эксклюзивной
    # блокировкой — на нынешних объёмах chunks это секунды. Значения
    # считает сама база, RLS тут не мешает (это DDL, а не UPDATE).
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', embed_text)", persisted=True), nullable=True))
    op.create_index('ix_chunks_fts', 'chunks', ['fts'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_fts', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'fts')
    # ### end Alembic commands ###
