"""qa log

Revision ID: 79e5752fabd3
Revises: d7e7594826a0
Create Date: 2026-09-25 11:52:52.308766

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa

from corp_ed.core.db_policies import rls_statements


# revision identifiers, used by Alembic.
revision: str = '79e5752fabd3'
down_revision: Union[str, Sequence[str], None] = 'd7e7594826a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=False),
    sa.Column('best_vector_distance', sa.Float(), nullable=True),
    sa.Column('best_fulltext_score', sa.Float(), nullable=True),
    sa.Column('answer_given', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('source_chunk_ids', sa.ARRAY(sa.Uuid()), server_default='{}', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('credits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('feedback', sa.SmallInteger(), nullable=True),
    sa.Column('miss_kind', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('feedback IN (-1, 1)', name='ck_qa_log_feedback'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_log_tenant_created', 'qa_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_qa_log_tenant_id'), 'qa_log', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Вопросы сотрудников — данные компании: та же изоляция, что у чанков.
    for statement in rls_statements(("qa_log",)):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_log_tenant_id'), table_name='qa_log')
    op.drop_index('ix_qa_log_tenant_created', table_name='qa_log')
    op.drop_table('qa_log')
    # ### end Alembic commands ###
