"""gap clusters

Revision ID: 925d32966b44
Revises: 019109ccbb0a
Create Date: 2026-09-25 12:28:24.124648

Отчёт о пробелах (BH-22): кластеры вопросов без ответа и их состав.
Обе таблицы — тенантские, под RLS с FORCE (core/db_policies.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from corp_ed.core.db_policies import rls_statements


# revision identifiers, used by Alembic.
revision: str = '925d32966b44'
down_revision: Union[str, Sequence[str], None] = '019109ccbb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('missing', sa.Text(), server_default='', nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('new', 'in_progress', 'resolved', 'dismissed')", name='ck_gap_clusters_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_clusters_tenant_id'), 'gap_clusters', ['tenant_id'], unique=False)
    op.create_index('ix_gap_clusters_tenant_priority', 'gap_clusters', ['tenant_id', 'priority'], unique=False)
    op.create_table('gap_cluster_questions',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('qa_log_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['gap_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qa_log_id'], ['qa_log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'qa_log_id')
    )
    op.create_index(op.f('ix_gap_cluster_questions_qa_log_id'), 'gap_cluster_questions', ['qa_log_id'], unique=False)
    op.create_index(op.f('ix_gap_cluster_questions_tenant_id'), 'gap_cluster_questions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for statement in rls_statements(("gap_clusters", "gap_cluster_questions")):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gap_cluster_questions_tenant_id'), table_name='gap_cluster_questions')
    op.drop_index(op.f('ix_gap_cluster_questions_qa_log_id'), table_name='gap_cluster_questions')
    op.drop_table('gap_cluster_questions')
    op.drop_index('ix_gap_clusters_tenant_priority', table_name='gap_clusters')
    op.drop_index(op.f('ix_gap_clusters_tenant_id'), table_name='gap_clusters')
    op.drop_table('gap_clusters')
    # ### end Alembic commands ###
