"""tenant seats

Revision ID: b5fcd7777592
Revises: 79e5752fabd3
Create Date: 2026-09-25 11:58:27.527406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fcd7777592'
down_revision: Union[str, Sequence[str], None] = '79e5752fabd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('seats', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###
    # Уже подключённым компаниям — 30 мест: нижняя граница сегмента по
    # досье (5.4). Настоящее число задаёт команда: cli set-seats.
    op.create_check_constraint("ck_tenants_seats_positive", "tenants", "seats > 0")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_tenants_seats_positive", "tenants", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'seats')
    # ### end Alembic commands ###
