"""material source file metadata

Revision ID: d7e7594826a0
Revises: 97d70ebf2e07
Create Date: 2026-09-25 11:48:39.900278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e7594826a0'
down_revision: Union[str, Sequence[str], None] = '97d70ebf2e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('source_filename', sa.String(length=255), nullable=True))
    op.add_column('materials', sa.Column('source_format', sa.String(length=16), nullable=True))
    op.add_column('materials', sa.Column('source_sha256', sa.String(length=64), nullable=True))
    op.add_column('materials', sa.Column('source_size', sa.Integer(), nullable=True))
    op.create_index('uq_materials_tenant_sha256', 'materials', ['tenant_id', 'source_sha256'], unique=True, postgresql_where=sa.text('source_sha256 IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_materials_tenant_sha256', table_name='materials', postgresql_where=sa.text('source_sha256 IS NOT NULL'))
    op.drop_column('materials', 'source_size')
    op.drop_column('materials', 'source_sha256')
    op.drop_column('materials', 'source_format')
    op.drop_column('materials', 'source_filename')
    # ### end Alembic commands ###
