"""qa_log model version

Revision ID: e512b41ef60f
Revises: 925d32966b44
Create Date: 2026-09-25 15:13:28.015496


BH-26: версия модели из ответа провайдера рядом с алиасом — /latest
переключается молча, метрики по журналу должны видеть настоящую модель.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e512b41ef60f'
down_revision: Union[str, Sequence[str], None] = '925d32966b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_log', sa.Column('llm_model_version', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_log', 'llm_model_version')
    # ### end Alembic commands ###
